### ISSUE TITLE
Defaults to server's IP

### ISSUE THREAD

**Issue by ishtangli** [4ch1m/pixoo-rest#1]
Fresh install of Ubuntu 20
Followed instructions
Set .env variables
Ran docker-compose up

Site is accessible but when I try to run a command, the IP it uses is the server's IP, not PIXOO_HOST

**Comment by 4ch1m** [comment]
Works for me.
Relevant parts are here...
https://github.com/4ch1m/pixoo-rest/blob/652bc908fd3764a38c406e5146550a5312986586/docker-compose.yml#L9-L10
... here ...
https://github.com/4ch1m/pixoo-rest/blob/652bc908fd3764a38c406e5146550a5312986586/app.py#L20
... and here:
https://github.com/4ch1m/pixoo-rest/blob/652bc908fd3764a38c406e5146550a5312986586/app.py#L33-L37

Can't help you any further with the little information you provide.

**Comment by ishtangli** [comment]
Sorry for the lack of information.

I installed Ubuntu 20 to a vm with a static IP of X.X.X.115. The Pixoo has an IP of X.X.X.225.

When I try to send text to the Pixoo, the curl script shows it tried to send it to X.X.X.115 which is the server's IP.

I confirmed that X.X.X.225 was set as PIXOO_HOST on the .env file.

Also tried to hard code the server's IP onto app.py and docker-compose.yml but it still pushes the payload to X.X.X.115.

Server is named pixoo-server if that matters.

Is 5000 the default port on the pixoo for pushing commands? Examples on the documentation uses 80.

**Comment by 4ch1m** [comment]
> When I try to send text to the Pixoo, the curl script shows it tried to send it to X.X.X.115 which is the server's IP.

This is the intended behaviour.
The (Swagger-)UI (and/or the generated curl-request) points to the locally running Python app/server. This app/server will then use the [Pixoo Library](https://github.com/SomethingWithComputers/pixoo) to send the actual commands to the Pixoo device.

In other words: The (Swagger-)UI itself does not directly talk to the Pixoo-device.
