### ISSUE TITLE
Initial setup via bluetooth

### ISSUE THREAD

**Issue by ghost** [4ch1m/pixoo-rest#13]
Would it be possible to sniff the bluetooth packets and reverse engineer the initial setup of the Pixoo64 over bluetooth, so that the Divoom app is no longer needed?

https://hackaday.com/2021/03/23/a-crash-course-on-sniffing-bluetooth-low-energy/

Thank you.

**Comment by 4ch1m** [comment]
Maybe.

https://github.com/pybluez/pybluez

Closing, since this is not an issue.
