### ISSUE TITLE
Feature Request: Multiple Pixoo 64's

### ISSUE THREAD

**Issue by MrMxyzptlk** [4ch1m/pixoo-rest#15]
I have Pixoo 64's in multiple rooms of my house; I would like the ability to have either multiple devices in your add on, or the ability to add additional instances of your addon. Thank you!

Love this by the way, I'm having a blast in Home Assistant with this.

**Comment by 4ch1m** [comment]
Hi there,

glad you like the app.

What you want can easily be achieved by firing up multiple instances of the container:

Build it...
```
docker build -t pixoo-rest .
```

Run it...
```
# office
docker run --rm -d -p 8080:5000 -e PIXOO_HOST=<your-pixoo-office-ip> pixoo-rest

# living room
docker run --rm -d -p 8081:5000 -e PIXOO_HOST=<your-pixoo-lr-ip> pixoo-rest

# bedroom
docker run --rm -d -p 8082:5000 -e PIXOO_HOST=<your-pixoo-bedroom-ip> pixoo-rest

# etc. ...
```
(Note: different host ports; different pixoo-hosts in env-var)

Just address the different instances (port 8080/8081/8082/etc.) accordingly from your (HomeAssistant) automations.

Et voilà! :boom: :sunglasses:

**Comment by MrMxyzptlk** [comment]
Thank you. I guess I will uninstall the HomeAssistant addon then and just create external docker instances.

I have a Home Assistant Yellow, so that is what I was hoping to run the 3 instances on.

**Comment by MrMxyzptlk** [comment]
Anyway I can get PULL access? I want to use the 'image' in DockerDesktop, and have WatchTower automatically update the container, when you update.

docker: Error response from daemon: pull access denied for github/4ch1m/pixoo-rest, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

**Comment by 4ch1m** [comment]
> Anyway I can get PULL access? I want to use the 'image' in DockerDesktop, and have WatchTower automatically update the container, when you update.
> 
> docker: Error response from daemon: pull access denied for github/4ch1m/pixoo-rest, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

Your request makes no sense.
I did not publish the image on hub.docker.com.
You have to build it for yourself.

**Comment by MrMxyzptlk** [comment]
Backyard mechanic here ; )
