### ISSUE TITLE
404s

### ISSUE THREAD

**Issue by davidonabus** [4ch1m/pixoo-rest#17]
Everything seemed to install ok, and I am able to connect to my Divoom devices, but I receive a 304/404 each time I try to execute a command from the webserver.

http://192.168.50.127:5000/pixoo-rest/sendGif
![image](https://github.com/4ch1m/pixoo-rest/assets/6895542/d5abe793-2167-457d-870d-d817f55829e8)

**Comment by 4ch1m** [comment]
Remove ...
```
# OPTIONAL: WSGI-conform way to configure a base-path/prefix-url (which may be needed when running behind a reverse proxy); NOTE -> this string must start with a slash!
SCRIPT_NAME=/pixoo-rest
```
... from your `.env` file.
