### ISSUE TITLE
Fonts Selection for drawText?

### ISSUE THREAD

**Issue by N1njaWTF** [4ch1m/pixoo-rest#18]
Hey :)

First of all, Thanks a lot for this contribution, its  a very great project and i appreciate it a lot. Im running it on my raspberry Pi and it works flawlessly.

Now to the Question / Issue I have. The sendText endpoint lets you choose between fonts for the text. Is that also available for drawText? Or why is there no fonts selection for the drawText method? Is it possible to add that maybe?

Thanks
Kind Regards

**Comment by 4ch1m** [comment]
Hi there,

Thank you.

The `drawText`-method doesn't offer font selection (yet).

That would have to be implemented in the pixoo-library:
https://github.com/SomethingWithComputers/pixoo/blob/0f750cfef7a3d720f3f68903730ca79f8e7a1412/src/pixoo/objects/pixoo.py#L204-L206
