### ISSUE TITLE
uploaded gif 1st frame glitched

### ISSUE THREAD

**Issue by poblabs** [4ch1m/pixoo-rest#3]
this is a great utility, thank you. i'm using it to upload gifs to the pixoo 64 and it's working great except for the 1st frame of each gif gets glitched - meaning colors are slightly off, sharpness too. super noticeable with looped gifs. 

i wonder if there's some fine tuning to that process that needs to take place?

**Comment by 4ch1m** [comment]
Glad you like the project.
As mentioned in the [README](/4ch1m/pixoo-rest/blob/master/README.md), [pixoo-rest](/4ch1m/pixoo-rest) makes use of the [pixoo](/SomethingWithComputers/pixoo)-library.
So all the heavy-lifting (image conversion, etc.) is being done there.

**Comment by 4ch1m** [comment]
> So all the heavy-lifting (image conversion, etc.) is being done there.

Let me take that back (I just checked the code). :smirk:

Actually, the GIF-conversion is the one exception where things are handled without the pixoo-library.

Check:
https://github.com/4ch1m/pixoo-rest/blob/c5a97ccee5511af42e78af329068c3d99f347ead/app.py#L240

However, there's not that much magic involved.
Simple usage of [pillow](https://pillow.readthedocs.io/en/stable/).
I can't reproduce the issues you describe.

**Comment by 4ch1m** [comment]
Can you provide a sample GIF?

**Comment by poblabs** [comment]
I found that section last night and was playing around with it. It looks like we need to use `thumbnail` instead of resize. But when I try that the Divoom crashes. And I can't figure out how to convert the thumbnail to RGB. 

Here's a sample gif that is normal, but when uploaded the first frame is glitchy

![giphy (3)](https://user-images.githubusercontent.com/3484775/191503354-81a43096-d823-465f-a109-7ff750152f9f.gif)

**Comment by 4ch1m** [comment]
The good news: I can reproduce the issue now. :smile:

The bad news: Resizing GIF images seems to be a major annoyance; I found a lot of attempts/code snippets in the web trying to fix similar issues (using standard Pillow features).

The root of the problem seems to be the very first frame of the GIF; which usually is a background with transparency-info, etc.

As a feasible workaround I've implemented an option (14de337829fb07a182cc8a8c22f2b0d47ef41249) to skip the first frame when resizing the GIF.

The example GIF you provided above looks fine now.

Could you have a look at this branch; and possibly try a few more GIFs?

Thanks.

**Comment by poblabs** [comment]
Awesome! So far so good. I had about 20 gifs I was testing with and all of them look great now. 

Another quick question - are you aware of a method to create a playlist of gifs without using their app? 

I see that you can assign a PicId, which I guess are slots to store animations. I don't see a way to cycle through them though?

https://github.com/4ch1m/pixoo-rest/blob/c5a97ccee5511af42e78af329068c3d99f347ead/app.py#L229

**Comment by 4ch1m** [comment]
> Another quick question - are you aware of a method to create a playlist of gifs without using their app?

Nope. Sorry.

> I see that you can assign a PicId, which I guess are slots to store animations. I don't see a way to cycle through them though?

There's an "official" documentation available here: http://doc.divoom-gz.com/web/#/12?page_id=93

The PicID is described there. However, I haven't looked into this in detail.
