### ISSUE TITLE
Copy python .env file in Dockerfile for docker container build

### ISSUE THREAD

**Issue by deepcoder** [4ch1m/pixoo-rest#5]
Hello and thank you for your work on this project!

After creating the .env file as specified in the documentation to the same directory as the app.py file, I need to add to the Dockerfile the following line after the 'COPY app.py .' line

```
COPY .env .
```

**Comment by 4ch1m** [comment]
The (same) `.env` file can be used when running the app ...

* directly

_AND_

* via `docker-compose`.

You should _NOT_ include the `.env` in the Dockerfile/Docker-image.

Please check: [Environment variables in Compose](https://docs.docker.com/compose/environment-variables/)
