### ISSUE TITLE
How to change listener from localhost to interface

### ISSUE THREAD

**Issue by lumberjackla** [4ch1m/pixoo-rest#6]
Hi,
first, I really like what you built and it works well in my tests.
But I would like to know what parameter to change in which file to have the service no longer only accepting requests on 127.0.0.1.
In your screenshot you use the interface IP and I would need that as well to access the REST from external.
Thanks

**Comment by 4ch1m** [comment]
It's up to you where you deploy/run the native Python app; and maybe put an appropriate proxy (Nginx, etc.) in front.
If you want to change the host, you could add the according param to the `run()` method here:

https://github.com/4ch1m/pixoo-rest/blob/addea2e8bfc0013abd5042c059e702dac4822c20/app.py#L309

Check the [Flask documentation](https://flask.palletsprojects.com/en/2.2.x/api/#flask.Flask.run) for details.

When using the app in containerized form you can simply build the container via the [Dockerfile](https://github.com/4ch1m/pixoo-rest/blob/master/Dockerfile), and run/deploy it anywhere you like (Docker, Kubernetes, etc.). The internal port is `5000`.
