### ISSUE TITLE
Sending Images / GIFS from FileSystem

### ISSUE THREAD

**Issue by xxric1993xx** [4ch1m/pixoo-rest#7]
Hello,
I install your Docker on my Synology NAS and with the Interface i can select, upload and send images / gifs to my pixoo 64. As I want to use the REST calls via CURL (Twitch Chat integration) and tried to execute the CURL commands via Shell but I can't figure out how I can send a local (file is on the Synology NAS) to the pixoo. No matter what syntax, folder will all permission I use, I always get a curl: (26) Failed to open/read local data from file/application error.

e.g. with this one:
`curl -X POST "http://192.168.178.32:8085/sendGif" -H "accept: application/json" -H "Content-Type: multipart/form-data" -F "gif=@/volume1/web/HEADICORN.gif;type=image/gif" -F "speed=100" -F "skip_first_frame=false"
curl: (26) Failed to open/read local data from file/application`

I hope you can help me out. Thanks in Advance!

**Comment by 4ch1m** [comment]
Hi,

I assume it's a permission problem on your Synology.
Make sure that `curl` has access to the referenced file/image.

Try running other commands on that file (from the same shell/path where you've executed the `curl` command).

e.g.
```
file /volume1/web/HEADICORN.gif
```

Anyway, this is not an issue of `pixoo-rest`, but of your setup/environment.
Maybe someone from the Synology-forums can help here.
