### ISSUE TITLE
Feature Request: POST GIF per URL

### ISSUE THREAD

**Issue by Azathoth88** [4ch1m/pixoo-rest#9]
It would be nice to be able to upload a GIF via a URL.
That means: I enter a URL, the API downloads the image and forwards it to the Pixoo.

**Comment by 4ch1m** [comment]
Hmmm... nice idea.
However, I'd like to keep the implementation/features of the REST-API as simple as possible.
Having to deal with the actual "download handling" (timeouts, caching, errors, etc.) would add additional complexity.
Also, the `pixoo-rest` app would need to have internet access for this... which might not be a use case for everyone.

So... I'm closing this for now.
Maybe more people will show interest for this in the future.

Thanks.
